version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mobidoc-postgres
    environment:
      POSTGRES_DB: mobidoc
      POSTGRES_USER: mobidoc
      POSTGRES_PASSWORD: mobidoc123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: mobidoc-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: mobidoc
      KC_DB_PASSWORD: mobidoc123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev

volumes:
  postgres_data: