version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mobidoc
      POSTGRES_PASSWORD: mobidoc123
      POSTGRES_MULTIPLE_DATABASES: keycloak,users,consultations,evaluations,notifications,locations,stats
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mobidoc-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: mobidoc
      KC_DB_PASSWORD: mobidoc123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mobidoc-network

volumes:
  postgres_data:

networks:
  mobidoc-network:
    driver: bridge