server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mobidoc_users
    username: ${DB_USER:mobidoc}
    password: ${DB_PASSWORD:mobidoc123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080/auth}
  realm: ${KEYCLOAK_REALM:mobidoc}
  resource: user-service
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username