server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mobidoc_users
    username: mobidoc
    password: mobidoc123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

keycloak:
  realm: mobidoc
  auth-server-url: http://localhost:8080
  resource: user-service
  public-client: true
  bearer-only: true